FROM bellsoft/liberica-openjdk-alpine:11.0.16
COPY ./src ./src-docker
RUN mkdir ./out-docker
RUN javac -sourcepath ./src-docker -d out-docker src-docker/Main.java 
CMD java -classpath ./out-docker Main
